import type { Metadata } from "next";
import "@/styles/globals.css";
export const metadata: Metadata = {
  title: {
    template: "%s | Moncef Letter",
    default: "Moncef Letter",
  },
  description: "Generated by Moncef Aissaoui",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        {children}
    </>
  );
}
