import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import  '@/styles/globals.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-dark-900 text-light-500 selection:bg-primary-900/50 selection:backdrop-blur-md selection:text-primary-500 ${GeistMono.className}`}
      >
        <Header />
        <main className="px-6 pt-16 sm:px-12 md:px-16 lg:px-36">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
